#!/usr/bin/env node
// Validates the Map against the real code, writes fairy-tale-mind/map/index.md,
// and exits non-zero on any hard error. Run via `npm run mind` / `prebuild`.
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const VAULT = join(ROOT, "fairy-tale-mind");
const ZONES_DIR = join(VAULT, "map", "zones");
const FLOWS_DIR = join(VAULT, "map", "flows");
const DEBT_DIR = join(VAULT, "tech-debt");
const INDEX = join(VAULT, "map", "index.md");

const errors = [];
const gaps = [];

function gitOut(args) {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function tracked(glob) {
  const out = gitOut(["ls-files", "--", glob]);
  return out ? out.split("\n").filter(Boolean) : [];
}

function grepFiles(needle, dirs) {
  const out = gitOut(["grep", "-l", "--fixed-strings", needle, "--", ...dirs]);
  return out ? out.split("\n").filter(Boolean) : [];
}

function routeExists(route) {
  // Resolve like the App Router does: route groups "(...)" are invisible in
  // URLs, so strip them from each page/route file's path before comparing.
  const want = route === "/" ? "" : route.replace(/^\//, "").replace(/\/$/, "");
  return tracked("app").some((f) => {
    const m = f.match(/^app\/(?:(.*)\/)?(?:page\.(?:tsx|jsx)|route\.tsx?)$/);
    if (!m) return false;
    const resolved = (m[1] ?? "")
      .split("/")
      .filter((s) => s && !(s.startsWith("(") && s.endsWith(")")))
      .join("/");
    return resolved === want;
  });
}

function anchorResolves(anchor) {
  const i = anchor.indexOf(":");
  const kind = anchor.slice(0, i);
  const val = anchor.slice(i + 1);
  if (kind === "id") return grepFiles(`id="${val}"`, ["app", "components"]).length > 0;
  if (kind === "route") return routeExists(val);
  return false;
}

function isStale(verifiedAt, globs) {
  if (!verifiedAt) return true;
  if (globs.length === 0) return false; // nothing to track → not stale (avoids `rev-list ..HEAD --` matching all commits)
  try {
    const out = execFileSync(
      "git",
      ["rev-list", `${verifiedAt}..HEAD`, "--", ...globs],
      { cwd: ROOT, encoding: "utf8" },
    ).trim();
    return out.length > 0;
  } catch {
    return true;
  }
}

function readNotes(dir, type) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => {
      const { data } = matter(readFileSync(join(dir, f), "utf8"));
      return { slug: f.replace(/\.md$/, ""), data };
    })
    .filter((n) => !type || n.data.type === type);
}

const zones = readNotes(ZONES_DIR, "zone");
const flows = readNotes(FLOWS_DIR, "flow");
const debt = readNotes(DEBT_DIR, "debt");

const rows = [];
const attic = [];

for (const z of zones) {
  const d = z.data;
  const owns = d.owns || {};
  const globs = owns.globs || [];
  const anchors = owns.anchors || [];
  const routes = owns.routes || [];

  if (d.status === "unmounted") {
    attic.push({ slug: z.slug, summary: d.summary || "" });
    continue;
  }

  for (const g of globs) {
    if (tracked(g).length === 0) errors.push(`zone "${z.slug}": glob "${g}" matches no tracked file`);
  }
  for (const a of anchors) {
    if (!anchorResolves(a)) errors.push(`zone "${z.slug}": anchor "${a}" does not resolve in code`);
  }
  for (const r of routes) {
    if (!routeExists(r)) errors.push(`zone "${z.slug}": route "${r}" does not resolve`);
  }
  for (const inv of d.invariants || []) {
    if (!inv.enforcedBy || inv.enforcedBy.length === 0)
      gaps.push(`zone "${z.slug}": invariant "${inv.rule}" has no enforcedBy`);
  }

  const stale = isStale(d.verifiedAt, globs);
  rows.push({
    slug: z.slug,
    status: d.status || "active",
    fresh: stale ? "⚠ stale" : "✓ fresh",
    summary: (d.summary || "").replace(/\|/g, "\\|"),
  });
}

for (const f of flows) {
  for (const step of f.data.steps || []) {
    if (step.startsWith("id:") || step.startsWith("route:")) {
      if (!anchorResolves(step)) errors.push(`flow "${f.slug}": step "${step}" does not resolve`);
    }
  }
}

rows.sort((a, b) => a.slug.localeCompare(b.slug));
const staleCount = rows.filter((r) => r.fresh.startsWith("⚠")).length;
const openDebt = debt.filter((n) => (n.data.status || "open") === "open").length;

let md = "";
md += "<!-- GENERATED by scripts/mind/generate.mjs — do not hand-edit. Run `npm run mind` or /map-sync. -->\n";
md += `<!-- mind:counts zones=${rows.length} stale=${staleCount} debt=${openDebt} -->\n`;
md += "# Map Index\n\n";
md += "| Zone | Status | Freshness | Summary |\n|---|---|---|---|\n";
for (const r of rows) md += `| [[${r.slug}]] | ${r.status} | ${r.fresh} | ${r.summary} |\n`;
md += "\n## ⚠ Verification gaps\n\n";
md += gaps.length ? gaps.map((g) => `- ${g}`).join("\n") + "\n" : "_None._\n";
md += "\n## Attic\n\n";
md += attic.length
  ? attic.map((a) => `- [[${a.slug}]] — ${a.summary}`).join("\n") + "\n"
  : "_Empty._\n";

writeFileSync(INDEX, md);
console.log(`🧠 Mind: ${rows.length} zones, ${staleCount} stale, ${openDebt} open debt, ${gaps.length} gaps.`);

if (errors.length) {
  console.error("\n✖ Mind verification FAILED:\n" + errors.map((e) => "  - " + e).join("\n"));
  process.exit(1);
}
